services:
  # Frontend - React приложение (статический сайт)
  - type: web
    name: putevoditel-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist

  # Chatbot - Python FastAPI приложение
  - type: web
    name: putevoditel-chatbot
    env: python
    buildCommand: pip install -r chatbot/requirements.txt
    startCommand: cd chatbot && python main.py

  # API - Node.js API
  - type: web
    name: putevoditel-api
    env: node
    buildCommand: cd api && npm install
    startCommand: cd api && npm start
